### ISSUE TITLE
Accounts

### ISSUE THREAD

**Issue by LARSABI** [dkmpostor/spotify-creator#1]
Hey,

the spotify accounts from both Inputs are not working.
Can you help me?

**Comment by LARSABI** [comment]
The E-Mail is linked with a spotify account but i think the password is the problem. If i try to reset it with an existing email, it works.

**Comment by dkmpostor** [comment]
It work

**Comment by LARSABI** [comment]
> It work

Not for me.  What could be the reason?

**Comment by LARSABI** [comment]
Whats means: Gagal Register undefined

**Comment by dkmpostor** [comment]
Failed to register . maybe ur acc is already registered

**Comment by dkmpostor** [comment]
'Gagal Register' mean failed to register .. and i dont know specific trouble of undefined , maybe ur password is too weak
