### ISSUE TITLE
Not Issue | Feature Request

### ISSUE THREAD

**Issue by v6r** [dkmpostor/spotify-creator#2]
Hey, 
nice tool. Would it possible to add the option to use usernames from a txt file

**Comment by dkmpostor** [comment]
noticed

**Comment by dkmpostor** [comment]
[https://ibb.co/wSjmX3b](url)

Like this right ?

**Comment by xsplas** [comment]
yeah, that would be great, but not only custom emails also custom usernames.

**Comment by dkmpostor** [comment]
username generated automatically by spotify , not customable

**Comment by xsplas** [comment]
ok. But the feature with custom email is also very useful
